# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMrE7rkkuwGzChtHnSJE_1fWdzLCFAQZ
"""

X = int(input())

print(f"{2 * X} minutos")