# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMrE7rkkuwGzChtHnSJE_1fWdzLCFAQZ
"""

A = int(input())
B = int(input())
C = int(input())
D = int(input())

DIFERENCA = (A * B - C * D)

print(f'DIFERENCA = {DIFERENCA}')