# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMrE7rkkuwGzChtHnSJE_1fWdzLCFAQZ
"""

nome_vendedor = str(input())
salario_fixo = float(input())
total_vendas = float(input())

total_receber = salario_fixo + (total_vendas * 0.15)

print(f'TOTAL = R$ {total_receber:.2f}')