# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMrE7rkkuwGzChtHnSJE_1fWdzLCFAQZ
"""

distancia_total = int(input())
combustivel_gasto = float(input())

consumo_medio = distancia_total / combustivel_gasto

print(f'{consumo_medio:.3f} km/l')