# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMrE7rkkuwGzChtHnSJE_1fWdzLCFAQZ
"""

peca1 = input().split(' ')
codigo1 = int(peca1[0])
quantidade1 = int(peca1[1])
valor1 = float(peca1[2])

peca2 = input().split(' ')
codigo2 = int(peca2[0])
quantidade2 = int(peca2[1])
valor2 = float(peca2[2])

total = quantidade1 * valor1 + quantidade2 * valor2

print(f'VALOR A PAGAR: R$ {total:.2f}')