# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMrE7rkkuwGzChtHnSJE_1fWdzLCFAQZ
"""

raio = float(input())
pi = 3.14159
volume = (4.0/3) * pi * (raio * raio * raio)

print(f'VOLUME = {volume:.3f}')