# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uMrE7rkkuwGzChtHnSJE_1fWdzLCFAQZ
"""

tempo_viagem = int(input())
velocidade_media = int(input())
carro = 12

distancia = tempo_viagem * velocidade_media
gasolina = distancia/carro

print(f'{gasolina:.3f}')